# Generated by Django 5.2.8 on 2025-11-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tokens",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Available tokens for AI Assistant and premium features",
            ),
        ),
    ]
