# Generated by Django 5.2.8 on 2025-11-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_userprofile_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="tokens_granted",
            field=models.BooleanField(
                default=False,
                help_text="Whether tokens were granted for completing this quiz",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_token_grant_date",
            field=models.DateField(
                blank=True,
                help_text="Date when tokens were last granted to the user",
                null=True,
            ),
        ),
    ]
