# Generated by Django 5.2.8 on 2025-11-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_quizsession_tokens_granted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="last_activity_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time user was active on quiz page",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="time_paused_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total time paused (when user was not on quiz page)",
            ),
        ),
    ]
