# Generated by Django 5.2.8 on 2025-11-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_quizsession_last_activity_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizsession",
            name="last_activity_at",
        ),
        migrations.RemoveField(
            model_name="quizsession",
            name="time_paused_seconds",
        ),
    ]
