# Generated by Django 5.2.8 on 2025-11-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_remove_quizsession_last_activity_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="is_paused",
            field=models.BooleanField(
                default=False, help_text="Whether the quiz timer is currently paused"
            ),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="paused_at",
            field=models.DateTimeField(
                blank=True, help_text="When the quiz was paused", null=True
            ),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="total_paused_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="Total time the quiz has been paused (in seconds)"
            ),
        ),
    ]
