# Generated by Django 5.1.5 on 2025-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_quizsession_is_paused_quizsession_paused_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["category", "exam_name", "name"]},
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_name",
            field=models.CharField(
                default="UPSC",
                help_text="Exam name like UPSC, ASI, CTET, STET",
                max_length=100,
            ),
        ),
    ]
