# Generated by Django 5.1.5 on 2025-12-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_add_exam_name_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="exam_category",
            field=models.CharField(
                default="AAAA", help_text="Exam category like AAAA", max_length=100
            ),
        ),
    ]
