# Generated by Django 5.1.5 on 2025-12-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_add_exam_category_to_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="User profile photo",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
